nunuhara/xsystem4

vm.h

This makes sure that `stack_ptr` is evaluated / updated after the evaluation of the macro argument.
`stack_push(stack_pop_var()[0].i += v);` was misbehaving in my environment because of this.

Fix undefined behavior of stack_{push,set}

---

include/gfx/private.h
shaders/blend_amap_alpha.f.glsl
shaders/copy.f.glsl
shaders/copy_key.f.glsl
shaders/copy_use_amap_border.f.glsl
shaders/copy_use_amap_under.f.glsl
shaders/hitbox.f.glsl
shaders/hitbox_noblend.f.glsl
shaders/render.f.glsl
src/video.c

MacOS [does not support](https://www.khronos.org/opengl/wiki/OpenGL_Context#OpenGL_3.2_and_Profiles) OpenGL compatibility profile, so the following changes had to be made to get graphics:
- Replaced `texture2D()` (deprecated in OpenGL 3.0) with `texture()` in shaders
- Renamed `texture` uniform variable to `tex`, to avoid name conflict
- Use VAO, which is mandatory in OpenGL 3 core profile

Fix OpenGL issues on MacOS

---

src/hll/SengokuRanceFont.c
src/system4.c

Adds `#include <limits.h>` for PATH_MAX.

Fix compile error on Mac

---

src/audio.c

This fixes an issue where `wav_unload_slot()` stops playing _all_ channels if `slot->channel == -1`.

Fix voice playback issue in Daibanchou

---

src/page.c
src/vm.c
test/Source/arrays.jaf

This fixes a memory corruption bug when reference values are copied into arrays, and also fix a test failure in `test_array_copy()`.

Fix vm_copy() for reference types

---

include/sact.h
include/scene.h
src/hll/SACT2.c
src/scene.c

It should return the maximum Z value among all sprites, not among visible sprites.
This fixes a bug in Rance VI where some UI elements are incorrectly Z-ordered.

Fix SACT2.SP_GetMaxZ

---

include/gfx/gfx.h
shaders/blend_amap_alpha.f.glsl
shaders/blend_amap_color.f.glsl
shaders/copy.f.glsl
shaders/copy_alpha_key.f.glsl
shaders/copy_color_reverse.f.glsl
shaders/copy_key.f.glsl
shaders/copy_use_amap_border.f.glsl
shaders/copy_use_amap_under.f.glsl
shaders/dungeon.f.glsl
shaders/dungeon.v.glsl
shaders/dungeon_skybox.f.glsl
shaders/dungeon_skybox.v.glsl
shaders/fill.f.glsl
shaders/fill_amap_over_border.f.glsl
shaders/fill_amap_under_border.f.glsl
shaders/hitbox.f.glsl
shaders/hitbox_noblend.f.glsl
shaders/render.f.glsl
shaders/render.v.glsl
src/fnl_render.c
src/text.c
src/video.c

This adds a compile-time flag to use OpenGL ES 3.0, paving the way to support more platforms (Android, WebGL, etc.)
I tested this on Raspberry Pi 4 (my primary Linux desktop environment). Rance VI's dungeon benchmark marked 170 fps with OpenGL ES3, while it was ~25 fps with the OpenGL3 software renderer.

Support OpenGL ES 3.0

---

include/dungeon/dungeon.h
include/dungeon/renderer.h
include/gfx/gfx.h
include/gfx/gl.h
meson.build
meson_options.txt
src/draw.c
src/dungeon/dungeon.c
src/dungeon/renderer.c
src/dungeon/skybox.c
src/meson.build
src/video.c

GLEW does not support OpenGL ES so it should not be used when targeting OpenGL ES.

Use OpenGL ES directly if `USE_GLES` is defined

---

src/system4.c
src/vm.c

It opens a URL in an appropriate way for the platform. It's available since SDL 2.0.14.

Use SDL_OpenURL for system.OpenWeb

---

include/gfx/gfx.h
include/gfx/private.h
src/input.c
src/video.c

We don't use SDL's rendering functions, so we have to scale the screen and translate the mouse positions ourselves.
I implemented this to make the graphics fit the screen on Android, but it could be useful on other platforms as well.

Make the window resizable

---

src/audio_mixer.c

This fixes a bug in Rance VI where sound effects stopped working after the first battle, caused by memory corruption in audio_mixer.c.
When `cb_loop()` called from `refill_stream()` set `ch->voice` to -1, out-of-bounds access occured later in `refill_stream()` at this line.
mixers[ch->mixer_no].mixer.voices[ch->voice].gain = gain;
`cb_loop()` shouldn't need to change `ch->voice`, because `refill_stream()` does that when `cb_loop()` returns false.

Fix out-of-bounds access in audio_mixer.c

---

src/hll/File.c
src/util.c

Values returned by `SACT2.System_GetDate` etc. should correspond to the Windows `SYSTEMTIME` structure, not `struct tm`.
This also fixes a bug where `get_time()` returns a value greater than 60 for `sec`.

Fix date/time getter functions

---

src/hll/MonsterInfo.c

Fixes a crash bug when attempted to get a string property of nonexistent motion.
This also fixes compiler warnings, and simplifies the code by using helper functions.

MonsterInfo: Fix SEGV, clean up

---

src/video.c

This fixes an issue where billboard objects are not drawn in some environments.
ReignEngine disables some vertex attributes when drawing billboards, but AMD's driver doesn't draw anything if any of those attributes are assigned to attribute index 0.
To avoid this, this explicitly binds "vertex_pos" attribute (which is always enabled) to index 0.
References:
https://community.khronos.org/t/gldisablevertexattribarray-not-working/67077/4
https://stackoverflow.com/questions/28818997/how-to-use-glvertexattrib

ReignEngine: Fix billboard rendering issue

---

include/reign.h
shaders/reign_shadow.f.glsl
src/3d/3d_internal.h
src/3d/reign.c
src/3d/renderer.c
src/hll/ReignEngine.c

This is used to compute Y-positions of map objects.
It is called quite often, so this implementation creates and caches a height map of the instance by (re)using the shader for shadow mapping.

ReignEngine: Implement CalcInstanceHeightDetection

---

src/video.c

This fixes an issue where text is not rendered on Android.
In OpenGL ES3.0, `GL_RED` is not a valid value for the `internalFormat` parameter of `glTexImage2D`.

Fix text rendering issue in OpenGL ES

---

include/reign.h
src/3d/3d_internal.h
src/3d/debug.c
src/3d/model.c
src/3d/reign.c
src/3d/renderer.c

Before this, the order of drawing was determined on an instance-by- instance basis. Instances with even a single transparent material were drawn after fully opaque instances.
After this, first the opaque meshes in all instances are drawn, and then the transparent meshes are drawn from the nearest to the farthest.

ReignEngine: Per-mesh control of drawing order

---

src/font_freetype.c

When creating a block-sized texture from a glyph, use the `bitmap_left` field of `FT_GlyphSlot` instead of just centering it horizontally.
This improves positioning of punctuation marks in Japanese text.
I'm not 100% sure if this works well in English games.
Before:
After:

font_freetype: Consider glyph information for horizontal positioning

---

include/xsystem4.h
src/3d/reign.c
src/asset_manager.c
src/dungeon/dungeon.c
src/hll/MonsterInfo.c

Some games have assets that are too large to mmap everything on a 32-bit address space. For example, TT3 has a total of 2.82GB of assets, which is too large for the 3GB address space limit of 32-bit Linux. On Android it's even stricter and mmaps of hundreds of MB can fail.

Do not use ARCHIVE_MMAP on 32-bit systems

---

src/vm.c
test/Source/lang.jaf

It corresponds to the `!==` operator.

Implement R_NOTE instruction

---

meson.build
meson_options.txt

This replaces `use_gles` boolean build option with `opengles` feature option. If OpenGL ES3 is available, it is preferred over desktop OpenGL. This can be overridden by `-Dopengles=disabled` meson flag.
This would help to catch problems like #93 early.

Use OpenGL ES by default

---

src/savedata.c

This fixes an issue where saved files could not be read on Windows.
On Windows if a file is opened in text mode, `ftell()` at EOF returns the file size in bytes, but `fread()` tries to read the specified number of characters (after removing carriage returns), resulting in an EOF error.
To avoid this problem, open save files in binary mode.

Windows: Fix read_save_file

---

include/debugger.h
src/debug.c
src/input.c
src/system4.c

Effective only if `--debug` command line flag is specified.
I've been using this for a while and found it very useful, because I could use `bt` command to check the code location or `scene` to examine the scene graph anytime.
What do you think?

Enter debugger REPL on middle-button click

---

src/movie.c

AliceSoft only uses MPEG-PS, but PlayMovie.dll is included in System4 SDK and can play any format supported by DirectShow. This fixes crash in `movie_load()` when given file was not a MPEG-PS.

Add error checking for movie format

---

src/effect.c

Some effects (e.g. `EFFECT_BLUR_CROSSFADE`) are slow on low-end Android devices. This adds frame rate control so that they won't take too long.

Allow frames to drop in sact_Effect()

---

src/asset_manager.c
src/system4.c

Command line paths containing non-ASCII characters now work on Windows.

Use UTF8-aware dirname/basename functions

---

include/vm.h
src/hll/InputDevice.c
src/hll/Timer.c
src/vm.c

The `nanosleep()` function in mingw-w64 often sleeps for more than the specified time. This causes a problem in Rance 6 combat scene, where the damage popup is noticeably slow.
This adds `vm_sleep()` that calls `SDL_Delay()` which uses high-resolution timer on Windows.

Add vm_sleep()

---

src/hll/DrawDungeon.c

This function is used for the underwater effect in GALZOO. It should be implemented as a post-processing effect, but in the meantime let's stub it out to avoid runtime error.

Add stub for DrawDungeon14.SetRasterScroll

---

src/hll/SACT2.c

Otherwise it `ERROR()`s in `gfx_set_framebuffer()` due to an incomplete framebuffer.
This happens when trying to display text without specifying a message window in SACT2. AliceSoft's implementation ignores this.

sact_SP_TextDraw: Early return if sprite size is zero

---

include/savedata.h
src/savedata.c
src/vm.c

After this, xsystem4 uses the global/group save format used by the original System4, instead of the JSON format. Existing JSON save files can still be loaded.
This makes save files interoperable between System4 and xsystem4 in some games, including Sengoku Rance and Toushin Toshi III.

Use global/group save file format compatible with System4

---

src/vm.c

SDL MessageBox functions expect UTF-8 strings even in Japanese-locale Windows.

Fix garbled characters in message box on Windows

---

src/dungeon/dungeon.c

Transparent objects should be drawn in order from furthest to nearest. In DrawDungeon, the actual viewpoint is slightly behind the camera, but this was not taken into account when sorting cells by distance.
Fixes #120

DrawDungeon: Fix cell drawing order

---

include/sprite.h
src/json.c
src/sprite.c

Text sprites hold the height of the text drawn on them, and `sact_SP_TextNewLine` increases the Y coordinate by this value if `nTextSize` is 0.
The `nTextSize` argument of `sact_SP_TextHome` affects this value.
Beat Blades Haruka depends on this behavior.

Fix sact_SP_TextNewLine when nTextSize is 0

---

src/hll/File2.c

Rance Quest uses yet another ad hoc archive format (`.rea`) for map data. This function opens an entry in the rea archive for reading.

Implement File2.OpenArchiveForRead

---

src/hll/StoatSpriteEngine.c

This fixes text layout issue in Daiteikoku and Rance Quest.
Before: ![before](https://github.com/nunuhara/xsystem4/assets/12679772/0c8f01d3-630c-4dad-b9ea-c4e098a885b8)
After:  ![after](https://github.com/nunuhara/xsystem4/assets/12679772/81da8dd0-22e8-4c12-ad82-2267681430b6)

StoatSpriteEngine: Clear cached font_size struct in SP_SetTextSpriteSize

---

src/audio_mixer.c

This ensures that SystemService.hll mixer functions can only access mixers specified in System40.ini, even if xsystem4 added more mixers.
Beat Blades Haruka checks the number and names of mixers, and refuses to open the config screen if they are not as expected.

SystemService can only access mixers specified in ini

---

src/hll/SystemService.c

This also rewrites the SetWindowSetting and GetWindowSetting functions based on the understanding gained from examining games after Haru Urare:
* Setting IDs are consistent across games.
* Settings 5 and 6 are added in Pastel Chime 3, both default true

SystemService: Implement "Wait Vsync" window setting

---

src/hll/MsgSkip.c

Some games (Ojou-sama o Iinari ni Suru Game and Double Sensei Life, as far as I know) pass "SaveData\\MsgSkip.asd" to MsgSkip.Init. So this change:
* uses savedir_path() to resolve the relative path, and
* removes the "SaveData\\" prefix, otherwise "SaveData/" will be duplicated in the resolved path.

Fix path resolution in MsgSkip.Init

---

include/dungeon/dungeon.h
include/dungeon/renderer.h
include/gfx/gfx.h
shaders/dungeon_raster.f.glsl
src/draw.c
src/dungeon/dungeon.c
src/dungeon/renderer.c
src/hll/DrawDungeon.c
src/hll/DrawGraph.c
src/hll/Gpx2Plus.c

It is implemented as a post-processing effect. The hack for the projection transform matrix has been removed, because now the image is flipped upside down in the post-processing stage.

DrawDungeon14: Implement raster effect

---

include/vm.h
src/format.c
src/hll/DrawDungeon.c
src/parts/parts.c
src/vm.c
test/Source/strings.jaf

* The "type" argument of `S_MOD` is 48 for bool, 56 for long int
* `%b`, `%c`, `%d` can consume any integer types (int, bool, or long int)
* If the value cannot be consumed, `S_MOD` should return the format string instead of an empty string
This also fixes incorrect return types in DrawDungeon14, introduced by #134.

Fix S_MOD for bool and long int

---

src/hll/Confirm3.c

For some reason, this function is renamed from GetHDDVolumeNumber only in Momoiro Guardian.
This also makes all Confirm3 functions HLL_QUIET_UNIMPLEMENTED.

Add Confirm3.Initialize

---

src/movie_ffmpeg.c
src/movie_plmpeg.c

When movie_free() was called in movie_load(), mixer_stream_stop(0) was mistakenly called and the music mixer was stopped.

Fix a bug that bgm did not work after movie load failed

---

src/hll/AnteaterADVEngine.c
src/hll/BanMisc.c
src/hll/ChrLoader.c
src/hll/DataFile.c
src/hll/MapLoader.c
src/hll/iarray.c
src/hll/iarray.h

BanMisc.{Save,Load}Struct now serializes structs in the same format as AliceSoft's implementation, rather than in JSON format. The old JSON format can also be loaded for backwards compatibility.
Fixes #140.

BanMisc: Use the same save format as AliceSoft's implementation

---

src/system4.c

Before this change, directory described in `System40.ini` was created even if `--save-folder` was specified.

Create savedir just before running VM

---

include/xsystem4.h
src/resume.c
src/system4.c
src/vm.c

Writing save files in RSM format is only enabled if `--save-format=rsm` command line flag is specified, because this implementation does not create save files that are fully compatible with the AliceSoft's implementation:
* There is no simple way to determine the RSM format version used by the game.
* There are several unknown fields in the RSM format.
* Empty arrays are represented as NULL pages in xsystem4, so type information of such objects cannot be saved.
These limitations are not a problem for the following use cases:
* Use the created save files only in xsystem4
* Load save files created by System40.exe
Also, RSM save files are much smaller and faster to read and write than JSON.

Add support for reading / writing System4 resume save files

---

CMakeLists.txt
include/vm.h
src/font_freetype.c
src/input.c
src/system4.c
src/video.c

This upstreams the xsystem4 side changes for xsystem4-android.
The code for touch event support is not enclosed in `#ifdef __ANDROID__`, so it will work on other platforms as well.

Android support

---

src/hll/SACT2.c

Since this is the surface to render to, it should not be added to the list of surfaces to draw from.
This is done by marking sprite -1 as hidden. Now `SACT2.SP_GetShow(-1)` returns 0 and `SACT2.SP_SetShow(-1, true)` raises a runtime error. This is consistent with the AliceSoft's implementation.

SACT2: Do not put sprite -1 (main surface) in the scene list

---

src/vm.c

Some games (e.g. Toushin Toshi 3) malfunction when `system.GetTime()` returns a negative number.
On many systems `clock_gettime(CLOCK_MONOTONIC)` returns the time since OS startup, but this wraps to a negative number (in signed 32-bit integer) after about 24.8 days.
As a mitigation, use `SDL_GetTicks()` instead, which returns the elapsed time since game startup.

system.GetTime(): Use SDL_GetTicks() instead of clock_gettime()

---

include/savedata.h
src/hll/File.c
src/savedata.c

This improves interoperability of save files in Rance6, GALZOO, etc. The old JSON format can still be loaded for backwards compatibility.

File.Read/Write: Use the same format as AliceSoft's implementation

---

src/hll/PassRegister.c

The old JSON format can still be loaded for backwards compatibility.

PassRegister: Use the same format as AliceSoft's implementation

---

src/video.c

This prevents `glTexImage2D()` from failing and resulting in an invalid texture if a width or height specified in `SACT2.SP_Create()` is greater than `GL_MAX_TEXTURE_SIZE`.
It is very rare and is probably a programming error in the game script. If the resulting texture is used for rendering, it may mess up the screen, but at least it won't crash.
Fixes https://github.com/kichikuou/xsystem4-android/issues/4.

gfx: Clamp texture size larger than GL_MAX_TEXTURE_SIZE

---

src/ffi.c
src/vm.c

Mamanyonyo is the second oldest System 4 game which uses ain v1 and Sys41VM.
This PR contains VM (i.e. non-HLL) changes required to run Mamanyonyo.

VM changes for Mamanyonyo

---

include/gfx/font.h
include/gfx/gfx.h
shaders/blend_rmap_color.f.glsl
shaders/dilate.f.glsl
src/3d/renderer.c
src/draw.c
src/dungeon/dungeon.c
src/hll/CharSpriteManager.c
src/hll/Gpx2Plus.c
src/hll/SengokuRanceFont.c
src/hll/StoatSpriteEngine.c
src/hll/vmDrawMsg.c
src/parts/construction.c
src/parts/text.c
src/sprite.c
src/text.c
src/video.c

This piece of code was added in a25f066 to eliminate text halo in the MangaGamer version of Sengoku Rance.
Text rendering is often a performance bottleneck. By omitting it for games other than Sengoku Rance, `gfx_draw_glyph()` becomes almost twice as fast.

Add a parameter to gfx_draw_glyph() for controlling blending behavior

---

meson.build
src/movie_ffmpeg.c

This fixes https://github.com/nunuhara/xsystem4/issues/159.
The minimum required ffmpeg version is now 5.1.

movie_ffmpeg: Use new FIFO API and channel layout

---

src/hll/Gpx2Plus.c

This fixes "Incomplete framebuffer" error in Daibanchou.

Gpx2Plus.Create() should fail if width <= 0 or height <= 0

---

include/effect.h
src/effect.c
src/hll/SACT2.c
src/hll/vmGraph.c

The effect API is slightly changed so that it can be used from pre-SACT graphics engines.

vmGraph changes for DALK Gaiden

---

include/parts.h
src/hll/AnteaterADVEngine.c
src/hll/DrawGraph.c
src/hll/DrawMovie.c
src/hll/GUIEngine.c
src/hll/GoatGUIEngine.c
src/hll/Gpx2Plus.c
src/hll/Timer.c
src/parts/motion.c

Notable changes:
* The `numerator` / `denominator` parameters of `AddMotion[HV]GaugeRate` are int in GoatGUIEngine but float in GUIEngine and PartsEngine.
* `AnteaterADVEngine.ADVLogList_AddText` has second parameter (`int WindowNo`) since Oyako Rankan.
This also avoids using non-void functions where a void function is expected. It is fine in most ABIs, but raises a runtime error in wasm32.

Fix signature mismatch in HLL_EXPORT functions

---

src/hll/SACT2.c

GALZOO calls this with `amp_x = 0`, to shake the screen vertically.

Add guard against division by zero in sact_QuakeScreen()

---

include/debugger.h
src/resume.c

On my low-end Android tablet, this reduced the time it took for the save/load screen to appear in お嬢様をいいなりにするゲーム from 5 seconds to 1 second.

Update rsave_read() parameters to specify read mode

---

CMakeLists.txt

This fixes build with Android NDK 27.
https://github.com/libsdl-org/SDL/issues/9792

Android: Update SDL2 to 2.30.7

---

include/xsystem4.h
src/savedata.c
src/system4.c

V5 is used until Daiteikoku, and v7 since Rance Quest. Since both are Ain v6, the save version is determined by the presence of the `MainVM` field in AliceStart.ini.

Add support for group save format v7

---

CMakeLists.txt
include/reign.h
src/3d/3d_internal.h
src/3d/collision.c
src/3d/model.c
src/3d/reign.c
src/hll/ReignEngine.c
src/meson.build

This is used for collision detection between a map object and the player character. The current implementation is very simple, only performing AABB intersection tests, but it is enough to allow the player to walk around the first dungeon in Rance Quest.

Initial implementation of TapirEngine.CalcInstance2DDetection

---

src/hll/vmDrawGauge.c

When `max` is 0, the gauge is drawn as empty.

Add guard against division by zero in vmDrawGauge.Draw()

---

shaders/dungeon_raster.f.glsl

`sample` is a reserved word in GLSL ES 3.0.

Fix compile error of dungeon_raster.f.glsl on WebGL

---

src/hll/StoatSpriteEngine.c

This fixes a problem in Vanish! where the opening movie was hidden behind other sprites.

StoatSpriteEngine: Make SP_GetMaxZ consider multisprites

---

include/gfx/font.h
src/hll/StoatSpriteEngine.c
src/text.c

This implementation creates a temporary "glyph" texture and draws it to the sprite using `gfx_draw_glyph()`.

Implement StoatSpriteEngine.SP_SetDashTextSprite

---

include/reign.h
meson.build
src/3d/3d_internal.h
src/3d/collision.c
src/3d/model.c
src/3d/reign.c
src/hll/ReignEngine.c
subprojects/cglm.wrap

Collision detection is based on a mesh named "collision" in the map's 3D model. The "collision" mesh specifies the area in which the character can move in the xz plane, and the y coordinate represents the height of the map at that point.
Now cglm 0.9.2 is required, for 2D AABB operations.

TapirEngine: Proper collision detection

---

src/3d/model.c

In Rance Quest (e.g. `mapF_ew01`), some materials use the same image for both color map and alpha map. In that case, the alpha channel of the color map can be used, so ignore the alpha map.

3d: Ignore alpha map if same as color map

---

src/hll/CGManager.c

This fixes a boot problem in Rance Quest Magnum.

CGManager.LoadArchive() should open archive in the game directory

---

include/reign.h
shaders/reign_outline.f.glsl
shaders/reign_outline.v.glsl
shaders/reign_shadow.v.glsl
src/3d/3d_internal.h
src/3d/model.c
src/3d/parser.c
src/3d/reign.c
src/3d/renderer.c

This implements outline (called "edge" in the game config) rendering of 3D objects, using the "inverted hull" method.

TapirEngine: Outline rendering

---

include/gfx/gfx.h
shaders/reign.f.glsl
shaders/reign.v.glsl
src/3d/3d_internal.h
src/3d/renderer.c
src/video.c

In TapirEngine, the following lighting features are not used:
- global ambient
- directional lights
- specular lights
- rim lights
- fog
(The setters / getters for these parameters are still there, but they don't affect rendering.)
This implementation disables those features in GLSL using `#ifdef`s. The C code that sets up the lighting remains almost unchanged -- `glGetUniformLocation()` will return -1 if the specified uniform variable name is not found, and `glUniform*(-1, ...)` will be no-op.

TapirEngine: Simplify lighting

---

include/reign.h
src/3d/3d_internal.h
src/3d/model.c
src/3d/parser.c
src/3d/reign.c
src/3d/renderer.c

In ReignEngine, alpha blending is the default. Alpha testing is used if the mesh/material has the (sprite) attribute.
In TapirEngine, alpha testing is the default. Alpha blending is used if the mesh/material has the (alpha) attribute.

TapirEngine: Fix alpha test / alpha blend conditions

---

src/video.c

This fixes "incomplete framebuffer" error in Haru Urare right after the game start, due to `gfx_set_framebuffer()` being called with a zero width texture. It was a regression introduced by commit 04d5237, which started using `gfx_set_framebuffer()` in `gfx_init_texture_rgba()`.
Ideally, we should avoid creating zero-area textures in upper layers (commit 3f18b18 was an attempt to do so), but this is difficult because there are many places that create textures. Let's just make sure that we don't generate unrecoverable errors.

Fix "incomplete framebuffer" error in gfx_init_texture_rgb(a)

---

include/debugger.h
src/debug.c
src/debug_info.c
src/debugger_cmd.c
src/meson.build
src/system4.c

This adds source-level debugging capabilities to the command-line debugger, utilizing debug information generated by sys4dc. The debug information format is documented at:
https://github.com/kichikuou/sys4dc/blob/master/docs/debug_info.md
The location of the debug information file can be specified with the `--debug-info` command-line flag. If not specified, xsystem4 will attempt to load it from `gamedir_path("src/debug_info.json")`.
When debug information is available, a breakpoint can be set at a specific line in a file using `breakpoint <file> <line>`. Also, `step` and `next` commands advance execution to the next source line (this is naively implemented by repeating instruction-level stepping).

debugger_cmd: Add support for source-level debugging

---

src/debugger_dap.c

* Add `allThreadsStopped` to Stopped event to indicate that stacktrace can be accessed
* StackTraceResponse should return most recent call first
* Fix instruction pointers of calling frames
The first two will improve compatibility with DAP clients other than xsys4dbg.

debugger_dap: minor fixes

---

include/xsystem4.h
src/resume.c
src/system4.c

Before this, the resume save format defaulted to JSON, which [could not be loaded by System40.exe](https://x.com/KanGT_f/status/1872635601314554105) and save/load was sometimes [too slow even on desktop environments](https://bsky.app/profile/kontaendless.itch.io/post/3lcsvkclurc2e).
In xsystem4-android the RSM format has been the default for 9 months and no problems have been reported. Let's make this the default on all platforms.

Use RSM save format by default

---

include/savedata.h
src/hll/SystemService.c
src/savedata.c
src/video.c

This setting has a significant impact on system load, so users may want xsystem4 to remember their preference.
This implementation uses a JSON format, while the AliceSoft's implementation saves it to a binary file (`WindowSetting.sav`).
This only records the `wait_vsync` setting, since the other fields in `window_settings` are currently no-op.

SystemService: Persist "wait vsync" setting to disk

---

src/hll/DrawGraph.c

This function draws a quad with arbitrary vertex and texture coordinates, but since it is actually only used to copy a rectangular area, this can be implemented using `gfx_copy_stretch()`.
This also adds HLL_TODO_EXPORTs for the DrawGraph functions defined but unused in Daiteikoku.

Daiteikoku: Implement DrawGraph.DrawDeformedSpriteBilinear

---

game_compatibility.md
src/hll/StoatSpriteEngine.c

`sprite_set_show()` is also used by `MultiSprite_SetAllShowMessageFrame`, causing interference.
Now `multisprite_update()` clears the sprite's texture when there's no CG, rather than hiding it.
Fixes #218.

StoatSpriteEngine: multisprite_update() should not use sprite_set_show()

---

CMakeLists.txt

It is the user's responsibility to ensure that these are found.
This allows xsystem4-android to update these library versions without making changes to xsystem4.

cmake: Use find_package() for zlib, SDL and freetype

---

src/hll/SystemService.c

Used in the trial versions of Rance 01 and Dorapeko.

SystemService: Add two functions

---

src/asset_manager.c

This fixes #227.
Rance 1 Digest Edition includes `Rance1.ain` and `RANCE1BA.ald`.

Use case-insensitive match for asset file names

---

include/sact.h
src/hll/ChipmunkSpriteEngine.c
src/hll/SACT2.c
src/hll/StoatSpriteEngine.c
src/parts/parts.c

In SACT2, if two sprites have the same Z value, they are rendered in increasing order of their sprite numbers. This behavior is documented in the SDK manual.
However, in later versions of the sprite engine (SACTDX, StoatSpriteEngine, ChipmunkSpriteEngine), sprites are drawn in the order they were created.
This fixes an issue in Rance Quest Magnum which relies on this behavior.
("ランスアタック" is shown above "初動LOCK")

SACTDX/Stoat/Chipmunk: render sprites in correct order for same Z

---

src/hll/DrawGraph.c

This fixes https://github.com/kichikuou/xsystem4-android/issues/12.
This game uses `DrawGraph.FillAMap()` to erase text drawn on the sprite, but our SengokuRanceFont implementation draws text on `sp->text.texture`.
For a detailed analysis of this issue and other possible solutions, see https://github.com/nunuhara/xsystem4/issues/237.

Fix overlapping text issue in MangaGamer Sengoku Rance

---

src/ffi.c

Since bool functions return a 1-byte value, the value of the upper 24 bits of `r.i` after `ffi_call` is undefined.
This actually led to a bug where `PassRegister.ExistText` returned incorrect values on Windows x64.

Fix bool return value of HLL functions

---

game_compatibility.md

Marking Rance Quest and Rance Quest Magnum as supported.
I was able to clear Rance Quest Magnum Integrated Edition (TADA patch v3.86E) without any issues.
I have only played the first few quests of the original Rance Quest, but I think it is safe to say that it works.
Fixes #209.

Update game compatibility table

---

src/3d/renderer.c

The `defines` string in load_shader() is prepended to the glsl file, but it was not terminated with a newline, so the resulting shader source looked like this:
#define REIGN_ENGINE 0
#define TAPIR_ENGINE 1
#define ENGINE 1/* Copyright (C) ...
*
* This program is free software; ...
...
This confused some OpenGL ES implementations, causing a syntax error. https://github.com/kichikuou/xsystem4-android/issues/15

3d: Ensure shader fragment ends with a newline

---

include/vm/page.h
src/ffi.c
src/hll/File.c
src/hll/vmFile.c
src/page.c
src/vm.c

Some classes in Dungeons & Dolls serialize themselves using `File.Write(this)` in their destructors. Because `File.Write` takes the argument by value, a copy of `this` is created. If the destructor is called on the copied `this`, it falls into an an infinite loop.

Do not call destructors for structs passed by value to HLL functions

---

include/xsystem4.h
src/hacks.c
src/vm.c

Early versions of System4 (`Sys42VM.dll` < 3.0) execute destructors for global variables on exit.
Dungeons & Dolls saves its game state in the destructors of global variables (`~CDataDoll()`, `~CDataItem()`, `~CDataMain()`), so the game was not saved in xsystem4 before this.
This behavior has some quirks:
* Destructors for variables on the call stack are not called on exit.
* Destructors are called in the reverse order of the global variable declarations.
* Inside a destructor, it is possible to access another global variable whose destructor has already been called (!).
Since this is a problematic behavior that was removed in later versions of Sys42VM, let's add minimal support for it as a game-specific hack.

Dungeons & Dolls: Call global variable destructors on exit

---

include/dungeon/dgn.h
include/dungeon/dtx.h
shaders/dungeon.f.glsl
src/dungeon/dgn.c
src/dungeon/dtx.c
src/dungeon/renderer.c

Without this:
With this (look at the border between the wall and floor):

DrawDungeon: Implement light mapping

---

src/sprite.c

The parts.f.glsl expects clip coordinates (`bot_left`/`top_right`) in bottom-left UV space, but `surface_area(x,y,w,h)` is stored in top-left sprite-local pixels. We were uploading TL values directly, so partial crops were clipped at the wrong vertical position. This in turn broke the Magnum Gauge in Rance Quest Magnum
Flip the surface_area.y inside the sprite's local rect before uploading it to the shader. (TL -> BL);
##
Without this:
With this:

fix: Y origin in prepare_chipmunk_shader

---

src/sprite.c

This fixes the Magnum Gauge (Rance Quest Magnum), similar to #269 but via a different approach. We now anchor the region selected by `surface_area(x,y,w,h)` back to the sprite origin (top-left). If the mask’s `x` or `y` is non-zero, we offset the draw rect so the masked region still appears at the sprite origin.
The gauge’s sprite rect starts below its container. As it fills, rect.y decreases (moving upward) and `surface_area` grows. However, the mask spans the bottom of the sprite and grows upward, while the game expects the sprite origin to come into view. Result: the visible area appears displaced
Before rendering a sprite we should check if it has a surface area and whether the x or y is not zero. If so we need to adjust the position we pass into the texture renderer so that the …

fix: anchor sprite surface_area at sprite origin

---

src/resume.c

Because `make_rsave()` determines the version of resume save based on the AIN version, it returns RSM v6 for Pastel Chime Continue. But this game requires the comment field added in RSM v7.
This solves the issue by upgrading to RSM v7 when comments are written to the save file.

Pastel Chime Continue: Make sure resume save v7 is used

---

src/debugger_dap.c

The DAP 'evaluate' request handler now correctly uses the 'frameId' argument to set the evaluation context.
This also fixes incorrect evaluation of expressions containing non-ASCII characters.

debugger_dap: Respect frameId in evaluate requests

---

src/dungeon/dungeon.c

This fixes #277.
Now `dungeon_load_dungeon()` and `dungeon_load_texture()` can be called multiple times without causing memory leaks.
This change also simplifies the loading process by removing `dungeon_finalize_loading()` helper function, as the map only depends on `ctx->dgn`, while the renderer only depends on `ctx->dtx`.

Fix leak of dungeon_renderer

---

include/debugger.h
src/debug.c
src/debugger_cmd.c
src/debugger_dap.c

Previously, the debugger displayed `ref int` variables like this:
ref_int: <unsupported-data-type>
<void>: <unsupported-data-type>
This commit introduces `dbg_variable_to_string()` to dereference these variables and display their underlying value. Both the command-line and DAP debugger interfaces have been updated to use this new functionality.

debugger: Display values of reference variables

---

src/input.c
src/video.c

This is part of the fix for https://github.com/kichikuou/xsystem4-android/issues/24.

Android: Do not use SDL_WINDOW_FULLSCREEN
