- src/audio.c
`SDL_RWFromConstMem` does not copy the memory buffer, so `archive_data` must be kept alive until the slot is unloaded.
> Fix use-after-free in audio.c when mmap is not available

- src/hll/Math.c
- test/Source/math.jaf
These are used in Big Bang Age.
> Math: Implement RandF, RandTableInit and RandTable

- include/vm.h
- src/savedata.c
- src/vm.c
> system.GlobalLoad() should not call destructors

- include/gfx/gfx.h
- shaders/blend_amap_color.f.glsl
- src/draw.c
- src/hll/DrawGraph.c
And fixes DrawGraph.SubDA_DAxSA.
> Implement DrawGraph.BlendAMapColor and DrawGraph.BlendDA_DAxSA

- README.md
- include/dungeon/dgn.h
- include/dungeon/dtx.h
- include/dungeon/dungeon.h
- include/dungeon/event_markers.h
- include/dungeon/mesh.h
- include/dungeon/skybox.h
- include/dungeon/tes.h
- include/gfx/gfx.h
- meson.build
- shaders/dungeon.f.glsl
- shaders/dungeon.v.glsl
- shaders/dungeon_skybox.f.glsl
- shaders/dungeon_skybox.v.glsl
- shaders/dungeon_sprite.f.glsl
- shaders/dungeon_sprite.v.glsl
- src/dungeon/dgn.c
- src/dungeon/dtx.c
- src/dungeon/dungeon.c
- src/dungeon/event_markers.c
- src/dungeon/mesh.c
- src/dungeon/skybox.c
- src/dungeon/tes.c
- src/ffi.c
- src/hll/DrawDungeon.c
- src/hll/SACT2.c
- src/meson.build
- src/video.c
- subprojects/cglm.wrap
With this and dummy implementation of `DrawGraph.CopyAMapHeightBlur` and `DrawGraph.CopyAMapWidthBlur`, the first dungeon of Rance VI is mostly playable.
> Initial implementation of DrawDungeon.hll (Rance VI)

- include/sprite.h
- src/hll/SACT2.c
- src/sprite.c
It's useful when testing graphics functions.
> Implement SACT2.SP_SetCGFromFile

- include/gfx/gfx.h
- shaders/copy_alpha_key.f.glsl
- src/draw.c
- src/hll/DrawGraph.c
> Implement DrawGraph.SpriteCopyAMap

- src/hll/Math.c
> Implement Math.BezierCurve

- subprojects/cglm.wrap
> Update cglm to v0.8.5

- include/plugin.h
- include/reign.h
- shaders/reign.v.glsl
- src/3d/3d_internal.h
- src/3d/model.c
- src/3d/parser.c
- src/3d/reign.c
- src/3d/renderer.c
- src/dungeon/dungeon.c
- src/hll/ReignEngine.c
- src/sprite.c
Also adds some debug infra for draw plugins.
> ReignEngine: Implement skeletal animation

- include/reign.h
- src/3d/debug.c
- src/3d/reign.c
- src/3d/renderer.c
- src/hll/ReignEngine.c
- src/meson.build
This also moves debug print functions to a separate file.
> ReignEngine: Implement background CG functions

- include/reign.h
- src/3d/3d_internal.h
- src/3d/reign.c
- src/3d/renderer.c
- src/hll/ReignEngine.c
Instance motions are updated with this function.
> Implement ReignEngine.BuildModel

- include/reign.h
- shaders/reign.f.glsl
- shaders/reign.v.glsl
- src/3d/3d_internal.h
- src/3d/debug.c
- src/3d/reign.c
- src/3d/renderer.c
- src/hll/ReignEngine.c
There are two types of fog, linear fog and atmospheric scattering. The formula for light scattering is incorrect (see the comment in `reign.v.glsl`) and therefore not physically correct.
> ReignEngine: Implement Fog

- include/reign.h
- shaders/reign.f.glsl
- src/3d/3d_internal.h
- src/3d/particle.c
- src/3d/reign.c
- src/3d/renderer.c
- src/hll/ReignEngine.c
This completes the implementation of the particle effect system, except for the camera quake effect.
> ReignEngine: Implement particle rendering

- src/audio_mixer.c
This fixes a bug in Toushin Toshi 3 where the audio thread crashes when battle ended, after exploring the second dungeon for `(INT_MAX / 44100)` milliseconds (~= 50 secs).
> Fix integer overflow in audio_mixer.c

- src/hll/Cursor.c
In Toushin Toshi 3, it is used only to show / hide the mouse cursor.
> Implement Cursor.Set HLL function

- include/reign.h
- src/3d/renderer.c
- src/hll/ReignEngine.c
Billboards of draw type 1 are drawn with additive blending.
> ReignEngine: Implement {Get,Set}InstanceDrawType

- src/effect.c
> Implement EFFECT_TV_SWITCH_ON

- shaders/effects/noise_crossfade.f.glsl
- shaders/effects/sepia_noise_crossfade.f.glsl
- src/effect.c
EFFECT_SEPIA_NOISE_CROSSFADE is frequently used in Toushin Toshi 3.
> Implement EFFECT_NOISE_CROSSFADE and EFFECT_SEPIA_NOISE_CROSSFADE

- game_compatibility.md
- include/reign.h
- src/3d/3d_internal.h
- src/3d/debug.c
- src/3d/model.c
- src/3d/parser.c
- src/3d/particle.c
- src/3d/reign.c
- src/3d/renderer.c
Although some advanced 3D features are not implemented yet and movies are missing, I was able to play Toushin Toshi 3 to the end.
> Improve ReignEngine, update game compatibility table

- include/sact.h
- src/hll/SACT2.c
- src/sprite.c
This fixes https://twitter.com/verygood123456/status/1636419682881388545.
> Change the second parameter of `sact_SP_SetShow` from bool to int

- src/hll/SystemService.c
- Implement `SystemService.GetGameVersion`
- Add stub for `SystemService.AddURLMenu`
These are used in 葉露 ～西の国の物語 (indie game).
> Add two SystemService functions

- src/audio_mixer.c
This fixes https://github.com/nunuhara/xsystem4/issues/117.
> Fix channel volume after fade completion

- src/hll/SACT2.c
> Add SACTDX.SP_DeleteAll

- src/hll/File.c
The same issue as https://github.com/nunuhara/libai5/pull/1 😅
> Fix compilation error with clang

- src/hll/vmArray.c
This also fixes a bug of vmArray.AroundRect (although it does not affect Mamanyonyo).
> Implement vmArray functions for DALK Gaiden

- include/vm.h
- include/vm/heap.h
- include/vm/page.h
- src/heap.c
- src/page.c
- src/resume.c
- src/vm.c
As discussed in https://github.com/nunuhara/libsys4/pull/34. See commit descriptions for details.
> Rework delegate implementation

- include/vm/page.h
- src/resume.c
- src/vm.c
Note that this doesn't make Rance 01's save files interoperable, because GUIEngine's serialization format is incompatible.
> resume: Support RSM v9 format

- src/hll/FileOperation.c
They should return base names, not full paths.
> Fix FileOperation.Get{File,Folder}List

- include/audio.h
- include/mixer.h
- src/audio.c
- src/audio_mixer.c
- src/hll/SoundFilePlayer.c
Using this, Widenyo can play user-provided BGM files in the `SaveData/MusicData` directory.
This depends on https://github.com/nunuhara/libsys4/pull/35.
> Implement SoundFilePlayer HLL

- src/hll/MsgSkip.c
This ensures that msgskip file is saved even if the app is killed by Android OS.
> Android: Call msgskip_save() when app goes to the background

- include/reign.h
- src/3d/reign.c
- src/hll/ReignEngine.c
- src/parts/parts.c
This fixes two issues:
- https://github.com/nunuhara/xsystem4/issues/180#issuecomment-2351079908
- The background of battle scene remains visible after the battle ends
> Fix two graphical bugs of Rance quest

- include/dungeon/dungeon.h
- src/dungeon/dungeon.c
- src/hll/DrawDungeon.c
In GALZOO Island, there are non-debugging code paths that use this.
> Implement DrawDungeon.SetWalkedAll

- src/page.c
- test/Source/arrays.jaf
* Fix sorting of strings and floats
* Avoid overflow in integer comparison
> Fix A_SORT

- shaders/reign.f.glsl
- shaders/reign.v.glsl
- src/3d/3d_internal.h
- src/3d/model.c
- src/3d/parser.c
- src/3d/renderer.c
3D objects can have a color per vertex, which is multiplied with the texture color.
> 3d: Implement vertex colors

- src/hll/IbisInputEngine.c
This enables wheel operations in Rance Quest.
> IbisInputEngine: Mouse wheel support

- src/3d/renderer.c
- Use `glm_look_anyup()` to avoid singularities when the shadow light direction is parallel to the up vector
- Fix bounding sphere calculation when there are multiple shadow casters
> 3d: Fix shadow rendering in Rance Quest

- src/hll/CharSpriteManager.c
- src/hll/StoatSpriteEngine.c
- src/parts/render.c
- src/parts/text.c
> Fix text rendering issues in Daiteikoku

- src/hll/AnteaterADVEngine.c
If the log exceeds 1000 pages, the oldest pages are discarded. This behavior is in line with AnteaterADVEngine.dll of Daiteikoku.
This prevents the log buffer from growing indefinitely, slowing down saves and loads.
> AnteaterADVEngine: Limit log size to 1000 pages

- game_compatibility.md
- include/gfx/gfx.h
- src/draw.c
- src/hll/DrawGraph.c
- src/hll/FileOperation.c
With this, I was able to play the game to the end.
> Daiteikoku support

- src/page.c
This fixes the weird ordering of the quest list in Rance Quest.
> A_SORT, A_SORT_MEM: Use stable sorting

- include/debugger.h
- include/xsystem4.h
- src/debug.c
- src/debug_info.c
- src/debugger_dap.c
- src/util.c
I tested this with the current HEAD of [vscode-system4](https://github.com/kichikuou/vscode-system4).
> debugger_dap: Source-level debugging

- include/gfx/gfx.h
- include/gfx/types.h
- src/effect.c
- src/movie_plmpeg.c
- src/video.c
Pure refactoring, no behavioral changes.
> gfx: Remove world_transform from struct texture

- src/parts/parts.c
The custom characters feature in Rance Quest calls `GoatGUIEngine.SetPartsCG()` with a name like `"<save>SaveData\\顔ＣＧ\\filename.png"`, which must be resolved with the save directory.
> PE_SetPartsCG_by_string_index: Accept `<save>` path

- src/vm.c
In System40.exe, `system.Error()` displays this dialog box:
`system.Error()` is used for critical errors, so its message should be presented to the user.
This makes `system.Error()` show a message box, allowing users to choose between stopping execution or continuing.
> Add message box for system.Error()

- include/dungeon/dgn.h
- src/dungeon/dgn.c
- src/dungeon/dtx.c
* `dtx_load_from_dtl()` loads lightmap textures.
* `dgn_calc_lightmap()` calculates lightmap texture index for each cell based on the state of the surrounding walls.
> Dungeons & Dolls: Enable light mapping

- src/hll/PastelChime2.c
> Fix flag index calculation in PastelChime2_Field_UpdateDoors

- game_compatibility.md
- src/dungeon/dungeon.c
- src/dungeon/generator.c
- src/hll/DrawDungeon.c
- src/hll/PastelChime2.c
- src/hll/SACT2.c
With these, I was able to finish the game.
> Various fixes for Pastel Chime Continue
